name: Automated labeling
run-name: Automated labeling to pull request.
on:
  pull_request:
    types: [opened, reopened]
jobs:
  put_release_label:
    runs-on: ubuntu-latest
    steps:
      - if: contains(github.head_ref, 'release')
        run: echo "ğŸ‰ Put release label event!"
        uses: andymckay/labeler@master
        with:
          add-labels: "release"
      - if: contains(github.head_ref, 'feature')
        run: echo "ğŸ‰ Put feature label event!"
        uses: andymckay/labeler@master
        with:
          add-labels: "feature"

